[project]
id = "tap-bootcamp-angular-app"
name = "TAP Bootcamp Angular App"
version = "1.0.0"

[build]
exclude = ["/README.md", ".git/"]

[[build.buildpacks]]
uri = "paketo-buildpacks/web-servers"

[[ build.env ]]
name="BP_NODE_RUN_SCRIPTS"
value="build"

[[ build.env ]]
name="BP_WEB_SERVER"
value="nginx"

[[ build.env ]]
name="BP_WEB_SERVER_ROOT"
value="dist/tap-bootcamp-angular-app"

[[ build.env ]]
name="BP_WEB_SERVER_ENABLE_PUSH_STATE"
value="true"
